# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartFootorage' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SmartFootorage
	pod 'Charts'
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Storage'
end
